// Generated by CoffeeScript 1.7.1
var cache, chatServer, fs, http, mime, path, send404, sendFile, serveStatic, server;

http = require('http');

fs = require('fs');

path = require('path');

mime = require('mime');

chatServer = require('../node_servers/chat_server');

cache = {};

server = http.createServer(function(request, response) {
  var absPath, fpath;
  fpath = false;
  if (request.url === '/') {
    fpath = 'public/index.html';
  } else {
    fpath = 'public/' + request.url;
  }
  absPath = '../' + fpath;
  return serveStatic(response, cache, absPath);
});

server.listen(3000, function() {
  return console.log('Server listening on port 3000.');
});

chatServer.listen(server);

send404 = function(res) {
  res.writeHead(404, {
    'Content-Type': 'text/plain'
  });
  res.write('Error 404: resource not found.');
  return res.end();
};

sendFile = function(res, fpath, fcontents) {
  res.writeHead(200, {
    'Content-Type': mime.lookup(path.basename(fpath))
  });
  return res.end(fcontents);
};

serveStatic = function(res, cache, absPath) {
  if (false) {
    return sendFile(res, absPath, cache[absPath]);
  } else {
    return fs.exists(absPath, function(exists) {
      if (exists) {
        return fs.readFile(absPath, function(err, data) {
          if (err) {
            return send404(res);
          } else {
            cache[absPath] = data;
            return sendFile(res, absPath, data);
          }
        });
      } else {
        return send404(res);
      }
    });
  }
};
